tagEnvironment        = "staging"
key_vault_name        = "srramkv123"
key_vault_resource_id = "/subscriptions/3d60da7d-bacf-4c0f-9333-16143cd9da70/resourceGroups/rgTerraformLabs/providers/Microsoft.KeyVault/vaults/srramkv123"
admin_pw_name         = "admin-pw"
location              = "eastus"
environment           = "dev"
rg_name               = "rgTerraformLabs"
vm_name               = "srramvm1"
